// The catalogs the app ships with. English is the source: every key exists
// there, and any other catalog may lack keys, which then show in English.
//
// Regenerated by `npm run i18n:translate` when it writes a catalog; adding a
// <locale>.json here by hand works too, as long as it is listed below.

import en from "./en.json"

export const SOURCE_LOCALE = "en"

export const catalogs: Record<string, unknown> = {
  en,
}
